---

- name: install go
  homebrew: name=go state=present

- name: install gofmt
  command: go get {{item}}
  with_items:
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/godoc
    - github.com/golang/lint/golint
    - github.com/nsf/gocode
    - golang.org/x/tools/cmd/gorename
    - github.com/rogpeppe/godef
    - github.com/zmb3/gogetdoc
    - github.com/ramya-rao-a/go-outline
    - github.com/tpng/gopkgs
    - github.com/acroca/go-symbols
    - golang.org/x/tools/cmd/guru
    - github.com/cweill/gotests/...
    - github.com/fatih/gomodifytags
    - github.com/josharian/impl