---

- hosts: localhost
  connection: local

  pre_tasks:

    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh
    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config
#     - name: personal ssh config in another location
#       become: yes
#       copy:
#         src: files/ssh_config
#         dest: /etc/ssh/ssh_config

    # needed for the vscode-plugin role
    - name: install vs-code cask
      homebrew_cask: name=visual-studio-code state=present

  roles:
    - git-config
    - homebrew
    - roderik.superlumic-osx-defaults
    - roderik.superlumic-cli
    - roderik.superlumic-computername
    - roderik.superlumic-vim
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: mattkg
          visual_studio_code_extensions:
            - bungcip.better-toml
            - dawhite.mustache
            - dunstontc.dark-plus-syntax
            - eamodio.gitlens
            - EditorConfig.EditorConfig
            - esbenp.prettier-vscode
            - golang.go
            - GrapeCity.gc-excelviewer
            - hashicorp.terraform
            - kddejong.vscode-cfn-lint
            - ms-azuretools.vscode-docker
            - ms-kubernetes-tools.vscode-kubernetes-tools
            - ms-python.python
            - ms-toolsai.jupyter
            - ms-vscode-remote.remote-containers
            - ms-vscode.cpptools
            - ms-vscode.powershell
            - ms-vsliveshare.vsliveshare
            - oderwat.indent-rainbow
            - oliversturm.fix-json
            - redhat.vscode-yaml
            - SirTori.indenticator
            - Tyriar.sort-lines
            - zhouronghui.propertylist
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - donjayamanne.python
            - haaaad.ansible
            - timonwong.ansible-autocomplete
            - timonwong.shellcheck
            - mdickin.markdown-shortcuts
            - darkriszty.markdown-table-prettify
            #- mauve.terraform
            - DavidAnson.vscode-markdownlint
            - PeterJausovec.vscode-docker
            - lukehoban.go
            - DanielThielking.aws-cloudformation-yaml
            - aws-scripting-guy.cform
            - tuxtina.json2yaml
            - Rubymaniac.vscode-direnv
          visual_studio_code_extensions_absent:
            - seanmcbreen.Spell
    

  tasks:
    - name: add necessary homebrew taps
      homebrew_tap: tap={{item}} state=present
      with_items:
        - versent/homebrew-taps
        - wallix/awless
        - aws/tap
        - TylerBrock/saw
        - pingidentity/devops


    - name: install personal brew apps
      homebrew: name={{item}} state=latest
      with_items:
        - mas
        - terraform
        - awscli
        - awless
        - jq
        - ack
        - python3
        - graphviz
        - shellcheck
#         - yarn
        - direnv
        - packer
        - freetype
        - jasper
        - libxml2
        - popt
        - fzf
        - jpeg
        - libxmlsec1
        - pyenv
        - utf8proc
        - autoconf
        - gawk
        - libyaml
        - watch
        - gdbm
        - kubectx
        - little-cms2
        - webp
        - gettext
        - kubernetes-cli
        - kubectl-argo-rollouts
        - helm
        - derailed/k9s/k9s
        - lz4
        - wget
        - aws-sam-cli
        - ghostscript
        - kustomize
        - mpfr
        - readline
        - x265
        - git
        - libde265
        - ncurses
        - rsync
        - xmlto
        - bash
        - git-extras
        - libevent
        - nettle
        - ruby
        - xxhash
        - bash-completion	
        - glib
        - libffi
        - oath-toolkit 
        - saml2aws
        - xz
        - bdw-gc
        - gmp
        - libgcrypt
        - oniguruma
        - saw
        - yamllint
        - brew-gem
        - gnu-getopt
        - libgpg-error
        - openexr
        - shared-mime-info
        - zbar
        - cfn-lint
        - gnu-indent
        - libheif
        - openjpeg
        - zsh-autosuggestions
        - coreutils
        - gnu-sed
        - libidn2
        - openssl
        - sqlite
        - zsh-completions
        - dcraw
        - gnu-tar
        - liblqr
        - p11-kit
        - stern
        - zsh-syntax-highlighting
        - gnutls
        - libomp
        - packer
        - telnet
        - zstd
        - docbook
        - grep
        - libpng
        - pcre
        - docbook-xsl
        - guile
        - libtasn1
        - pcre2
        - tmux
        - eksctl
        - helm
        - libtiff
        - ping-devops
        - tree
        - findutils
        - ilmbase
        - libtool
        - pkg-config
        - ufraw
        - fontconfig
        - imagemagick
        - libunistring
        - derailed/popeye/popeye
        - unbound
        - k9s
        - newman
        - kustomize
        - argocd
        - starship

    # - name: install python modules
    #   pip: name={{item}} state=latest
    #   with_items:
    #     - credstash

    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - 1password
        - 1password-cli
        - slack #installed via AppStore
        - google-chrome
        - chrome-devtools
        - firefox
        - tidal
        - grammarly
        - dropbox
        #- vmware-fusion
        - docker
        - plex-media-player
        - evernote
        - vlc
        #- sourcetree
        #- tunnelblick
        #- kindle
        - microsoft-office
        - microsoft-teams
        - p4v
        #- skype-for-business
        - iterm2
        - superduper
        - caffeine
        #- the-unarchiver
        - keka
        #- little-snitch
        - istat-menus
        - oversight
        # - spectacle
        - grandperspective
        - hex-fiend
        - omnigraffle
        #- dnscrypt
        - private-internet-access
#         - expressvpn
        - transmission
        - roon
        - zoom
        - cyberduck
        - postman
        - xld
        - synergy
        - cheatsheet
        - apache-directory-studio
#         - skitch
        - sketchbook
        - discord
#         - intel-power-gadget
#         - retroactive


    # - name: install personal cask utilities
    #   homebrew_cask: name={{item}} state=present install_options='appdir=/Applications/Utilities'
    #   with_items:
    #     - lots of things seem unhappy to be anywhere but /Applications these days

    - name: '[App Store] See which apps are already installed'
      command: bash -c "mas list | cut -f 1 -d ' '"
      register: mas_list
    - name: '[App Store] Install Mac App Store applications'
      command: mas install {{ item.id }}
      when: item.id not in mas_list.stdout_lines
      with_items:
        - { id: '409183694', name: 'Keynote' }
#        - { id: '1142578753', name: 'OmniGraffle' }
        - { id: '1333542190', name: '1Password 7' }
        - { id: '1289583905', name: 'Pixelmator Pro' }
        - { id: '408981426', name: 'Aperture' }
#         - { id: '1384080005', name: 'Tweetbot' }
        - { id: '409203825', name: 'Numbers' }
        - { id: '409201541', name: 'Pages' }
        - { id: '408981434', name: 'iMovie' }
        - { id: '682658836', name: 'GarageBand' }
        - { id: '634148309', name: 'Logic Pro' }
#         - { id: '425424353', name: 'The Unarchiver' }
#         - { id: '1529448980', name: 'Reeder 5.' }
#         - { id: '1482454543', name: 'Twitter' }
#        - { id: '1462114288', name: 'Grammarly for Safari' }
        - { id: '406056744', name: 'Evernote' }
        - { id: '1295203466', name: 'Microsoft Remote Desktop' }
        


  vars:
    - computername: 'silversliver'
    - git_user_name: mattkg
    - git_user_email: mattkg@versent.com.au
    - preferred_shell: zsh
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: left
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 2
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      # - domain: 'com.apple.menuextra.clock'
      #   key: 'DateFormat'
      #   type: string
      #   value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'PMPrintingExpandedStateForPrint'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
      - domain: 'NSGlobalDomain'
        key: 'NSQuitAlwaysKeepsWindows'
        type: boolean
        value: false
      - domain: 'com.apple.desktopservices'
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      - domain: 'com.apple.print.PrintingPrefs'
        key: 'Quit When Finished'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeInternalDebugMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeDevelopMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'WebKitDeveloperExtras'
        type: boolean
        value: true
